### ISSUE TITLE
Unable to import app that was just exported from the same RVD instance

### ISSUE THREAD

**Issue by ivelin** [Mobicents/RestComm#221]
Related to #220. See video in #220.

Here is the stack trace:
```
18:17:23,802 INFO  [org.mobicents.servlet.restcomm.rvd.http.resources.RasRestService] (http-/0.0.0.0:8080-4) uploading new ras app

18:17:23,807 ERROR [org.mobicents.servlet.restcomm.rvd.http.resources.RasRestService] (http-/0.0.0.0:8080-4) Cannot find file: /var/folders/0t/wchmjqbx1cg51jjkzbh_3tyr0000gn/T/1429136243803-0/app/info.xml: org.mobicents.servlet.restcomm.rvd.storage.exceptions.StorageEntityNotFound: Cannot find file: /var/folders/0t/wchmjqbx1cg51jjkzbh_3tyr0000gn/T/1429136243803-0/app/info.xml

at org.mobicents.servlet.restcomm.rvd.storage.WorkspaceStorage.loadModelFromXMLFile(WorkspaceStorage.java:208) [classes:]

at org.mobicents.servlet.restcomm.rvd.storage.WorkspaceStorage.loadModelFromXMLFile(WorkspaceStorage.java:202) [classes:]

at org.mobicents.servlet.restcomm.rvd.RasService.importAppToWorkspace(RasService.java:137) [classes:]

at org.mobicents.servlet.restcomm.rvd.http.resources.RasRestService.newRasApp(RasRestService.java:259) [classes:]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_60]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_60]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_60]

at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_60]

at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350) [jersey-server-1.13.jar:1.13]

at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.13.jar:1.13]

at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.13.jar:1.13]

at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.13.jar:1.13]

at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final.jar:1.0.2.Final]

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final.jar:7.2.0.Final]

at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_60]
```

**Comment by otsakir** [comment]
@ivelin, the problem here is that the application is exported as a **raw** rvd project package and then imported as a RAS package. Raw packages can be imported only from RVD itself. See screenshot:

The labels the help tips and the error messages need improvement for sure though. This is not the first time a user gets confused with two different export formats.

![import_raw_projects](https://cloud.githubusercontent.com/assets/8972800/7223807/fe2b7e7c-e730-11e4-860d-59c2fa963eb3.png)

**Comment by ivelin** [comment]
Thank you, @otsakir . @scottbarstow and I could not spot this option. Learning on the fly :)
