### ISSUE TITLE
Exception during DID registration from DID Provider

### ISSUE THREAD

**Issue by gvagenas** [Mobicents/RestComm#276]
When trying to register a DID after searching using a DID provision provider, the registration fails locally with the following exception

```java
16:31:41,432 SEVERE [com.sun.jersey.spi.container.ContainerResponse] (http-/10.146.211.185:8080-12) The RuntimeException could not be mapped to a response, re-throwing to the HTTP container: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'pure_sip' cannot be null
### The error may involve org.mobicents.servlet.sip.restcomm.dao.IncomingPhoneNumbersDao.addIncomingPhoneNumber-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO restcomm_incoming_phone_numbers (sid, date_created, date_updated, friendly_name, account_sid, phone_number, api_version,     voice_caller_id_lookup, voice_url, voice_method, voice_fallback_url, voice_fallback_method, status_callback, status_callback_method,     voice_application_sid, sms_url, sms_method, sms_fallback_url, sms_fallback_method, sms_application_sid, uri, voice_capable, sms_capable,     mms_capable, fax_capable, pure_sip) VALUES(?,     ?, ?, ?, ?, ?, ?, ?,     ?, ?, ?, ?, ?, ?,     ?, ?, ?, ?, ?, ?, ?,     ?, ?, ?, ?, ?);
### Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'pure_sip' cannot be null
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:137) [mybatis-3.2.2.jar:3.2.2]
        at org.mobicents.servlet.restcomm.dao.mybatis.MybatisIncomingPhoneNumbersDao.addIncomingPhoneNumber(MybatisIncomingPhoneNumbersDao.java:64) [restcomm.dao-7.3.0.1131.jar:]
        at org.mobicents.servlet.restcomm.http.IncomingPhoneNumbersEndpoint.putIncomingPhoneNumber(IncomingPhoneNumbersEndpoint.java:315) [restcomm.http-7.3.0.1131.jar:]
        at org.mobicents.servlet.restcomm.http.IncomingPhoneNumbersJsonEndpoint.putIncomingPhoneNumber(IncomingPhoneNumbersJsonEndpoint.java:55) [restcomm.http-7.3.0.1131.jar:]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_65]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.spi.coI thinkntainer.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.13.jar:1.13]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.13.jar:1.13]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.13.jar:1.13]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final.jar:1.0.2.Final]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.0.jar:1.2.0]
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.0.jar:1.2.0]
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:380) [shiro-core-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.mobicents.servlet.sip.startup.SipStandardContextValve.invoke(SipStandardContextValve.java:253)
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_65]
Caused by: java.sql.SQLIntegrityConstraintViolationException: Column 'pure_sip' cannot be null
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:132)
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288)
        at org.mariadb.jdbc.MySQLPreparedStatement.execute(MySQLPreparedStatement.java:141)
        at org.jboss.jca.adapters.jdbc.CachedPreparedStatement.execute(CachedPreparedStatement.java:297)
        at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.execute(WrappedPreparedStatement.java:404)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148) [mybatis-3.2.2.jar:3.2.2]
        ... 50 more
Caused by: org.mariadb.jdbc.internal.common.QueryException: Column 'pure_sip' cannot be null
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:942)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281)
        ... 59 more

16:31:41,441 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/restcomm].[Jersey]] (http-/10.146.211.185:8080-12) JBWEB000236: Servlet.service() for servlet Jersey threw exception: org.mariadb.jdbc.internal.common.QueryException: Column 'pure_sip' cannot be null
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:942)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281)
        at org.mariadb.jdbc.MySQLPreparedStatement.execute(MySQLPreparedStatement.java:141)
        at org.jboss.jca.adapters.jdbc.CachedPreparedStatement.execute(CachedPreparedStatement.java:297)
        at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.execute(WrappedPreparedStatement.java:404)
        at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148) [mybatis-3.2.2.jar:3.2.2]
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:137) [mybatis-3.2.2.jar:3.2.2]
        at org.mobicents.servlet.restcomm.dao.mybatis.MybatisIncomingPhoneNumbersDao.addIncomingPhoneNumber(MybatisIncomingPhoneNumbersDao.java:64) [restcomm.dao-7.3.0.1131.jar:]
        at org.mobicents.servlet.restcomm.http.IncomingPhoneNumbersEndpoint.putIncomingPhoneNumber(IncomingPhoneNumbersEndpoint.java:315) [restcomm.http-7.3.0.1131.jar:]
        at org.mobicents.servlet.restcomm.http.IncomingPhoneNumbersJsonEndpoint.putIncomingPhoneNumber(IncomingPhoneNumbersJsonEndpoint.java:55) [restcomm.http-7.3.0.1131.jar:]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_65]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_65]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_65]
        at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_65]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350) [jersey-server-1.13.jar:1.13]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416) [jersey-servlet-1.13.jar:1.13]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538) [jersey-servlet-1.13.jar:1.13]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716) [jersey-servlet-1.13.jar:1.13]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.2.Final.jar:1.0.2.Final]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.0.jar:1.2.0]
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.0.jar:1.2.0]
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:380) [shiro-core-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.0.jar:1.2.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.mobicents.servlet.sip.startup.SipStandardContextValve.invoke(SipStandardContextValve.java:253)
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:145) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:336) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:856) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920) [jbossweb-7.2.0.Final.jar:7.2.0.Final]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_65]```

**Comment by croufay** [comment]
There was a problem with the DB schema that prevented the update. The pure_sip column should be nullable


restcomm.restcomm_incoming_phone_numbers;' 
+------------------------+-------------+------+-----+---------+-------+
| Field                  | Type        | Null | Key | Default | Extra |
+------------------------+-------------+------+-----+---------+-------+
| sid                    | varchar(34) | NO   | PRI | NULL    |       |
| date_created           | datetime    | NO   |     | NULL    |       |
| date_updated           | datetime    | NO   |     | NULL    |       |
| friendly_name          | varchar(64) | NO   |     | NULL    |       |
| account_sid            | varchar(34) | NO   |     | NULL    |       |
| phone_number           | varchar(30) | NO   |     | NULL    |       |
| api_version            | varchar(10) | NO   |     | NULL    |       |
| voice_caller_id_lookup | tinyint(1)  | NO   |     | NULL    |       |
| voice_url              | mediumtext  | YES  |     | NULL    |       |
| voice_method           | varchar(4)  | YES  |     | NULL    |       |
| voice_fallback_url     | mediumtext  | YES  |     | NULL    |       |
| voice_fallback_method  | varchar(4)  | YES  |     | NULL    |       |
| status_callback        | mediumtext  | YES  |     | NULL    |       |
| status_callback_method | varchar(4)  | YES  |     | NULL    |       |
| voice_application_sid  | varchar(34) | YES  |     | NULL    |       |
| sms_url                | mediumtext  | YES  |     | NULL    |       |
| sms_method             | varchar(4)  | YES  |     | NULL    |       |
| sms_fallback_url       | mediumtext  | YES  |     | NULL    |       |
| sms_fallback_method    | varchar(4)  | YES  |     | NULL    |       |
| sms_application_sid    | varchar(34) | YES  |     | NULL    |       |
| uri                    | mediumtext  | NO   |     | NULL    |       |
| voice_capable          | tinyint(1)  | YES  |     | NULL    |       |
| sms_capable            | tinyint(1)  | YES  |     | NULL    |       |
| mms_capable            | tinyint(1)  | YES  |     | NULL    |       |
| fax_capable            | tinyint(1)  | YES  |     | NULL    |       |
 pure_sip               | tinyint(1)  | NO  |     | NULL    |       |
+------------------------+-------------+------+-----+---------+-------+

modify table
'ALTER TABLE  restcomm.restcomm_incoming_phone_numbers MODIFY COLUMN pure_sip boolean NULL;'

 pure_sip               | tinyint(1)  | YES  |     | NULL    |       |

**Comment by hrosa** [comment]
I will modify the script to make the field nullable.
But in my opinion it is strange to allow nullable boolean field. I believe this needs to be reviewed in the future and make RestComm handle this situation in a more elegant manner (like defining some default values).

**Comment by hrosa** [comment]
Created issues CLOUDOPS-76 and CLOUDOPS-77 to fix the update scripts.

**Comment by croufay** [comment]
please see issue below that will take care of the schema upgrade from restcomm
https://github.com/Mobicents/RestComm/issues/308
