### ISSUE TITLE
Sporadically 200 OK reponse to BYE request isn't replied to the initiator

### ISSUE THREAD

**Issue by atsakiridis** [Mobicents/RestComm#288]
Scenario is this (notice that both olympus and iphone are registered with restcomm):

- Olympus calls iphone
- iphone answers
- iphone hangs up (but doesn't receive 200 OK to the BYE from restcomm so it leaves media active)
- Olympus calls iphone again
- iphone realizes the previous transactions isn't over and bails

From Restcomm (version 7.3.0.641) log there's this exception right after it receives the 200 OK from Olympus and before it sends it to iphone:

12:37:30,637 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-230) Can not bind object to session that has been invalidated!!: java.lang.IllegalStateException: Can not bind object to session that has been invalidated!!
at org.mobicents.servlet.sip.core.session.SipSessionImpl.setAttribute(SipSessionImpl.java:1226)
at org.mobicents.servlet.sip.message.MobicentsSipSessionFacade.setAttribute(MobicentsSipSessionFacade.java:182)
at org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper.forwardResponse(B2BUAHelper.java:423) [restcomm.telephony.api-7.3.0.641.jar:]
at org.mobicents.servlet.restcomm.telephony.CallManager.response(CallManager.java:1015) [restcomm.telephony-7.3.0.641.jar:]
at org.mobicents.servlet.restcomm.telephony.CallManager.onReceive(CallManager.java:652) [restcomm.telephony-7.3.0.641.jar:]
at akka.actor.UntypedActor$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

Like the sip session is invalidated prematurely or something?

**Comment by gvagenas** [comment]
@atsakiridis Antonis can you make a new test call and capture the trace at Restcomm side so we can see SIP traffic from both clients?
