### ISSUE TITLE
Olympus WebRTC Closes SIP session that results in NPE when sending text Messages

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#570]
07:39:24,330 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-924) P2P, Message from: alice redirected to
 registered client: charles
07:39:24,330 INFO  [com.telestax.servlet.MonitoringService] (RestComm-akka.actor.default-dispatcher-924) Processing Message: "org.mobicents.servlet.re
stcomm.telephony.TextMessage sender : class akka.actor.RepointableActorRef
07:39:24,373 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (SIP-TCP-Core-PipelineThreadpool-14) <message
from="192.168.1.3:59673"
to="192.168.1.3:5082"
time="1445866764372"
isSender="false"
transactionId="z9hg4bk25cea178_57a5b08a_3f6558c0-fe3e-418f-92ab-ecf2c1a6bdb8"
callId="fcb815de5f33c51908f91728dfbbbc63@192.168.1.3"
firstLine="SIP/2.0 200 OK"
>
<![CDATA[SIP/2.0 200 OK
Call-ID: fcb815de5f33c51908f91728dfbbbc63@192.168.1.3
CSeq: 1 MESSAGE
From: <sip:alice@192.168.1.3>;tag=05272380_2c3efd52_57a5b08a_25cea178
To: <sip:charles@telestax.com>;tag=1445866764369
Max-Forwards: 70
Via: SIP/2.0/WS 192.168.1.3:5082;branch=z9hG4bK25cea178_57a5b08a_3f6558c0-fe3e-418f-92ab-ecf2c1a6bdb8;rport
Content-Type: text/plain
Contact: <sip:charles@192.168.1.3:59673;transport=ws>
Content-Length: 5

hello]]>
</message>

07:39:24,374 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-7) Invalidating the sip session (05272380_2c3efd52_57a5b08a_25cea178;fcb815de5f33c51908f91728dfbbbc63@192.168.1.3;25cea178;RestComm)
07:39:24,375 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-924) SIP SESSION is NULL
07:39:24,375 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-921) getting INSTANCE OF class  class org.mobicents.servlet.sip.message.Servlet3SipServletResponseImpl
07:39:24,374 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-7) Invalidating the sip session (05272380_2c3efd52_57a5b08a_25cea178;fcb815de5f33c51908f91728dfbbbc63@192.168.1.3;25cea178;RestComm)
07:39:24,375 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-924) SIP SESSION is NULL
07:39:24,375 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-921) getting INSTANCE OF class  class org.mobicents.servlet.sip.message.Servlet3SipServletResponseImpl
07:39:24,376 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-921) ((SipServletResponse) message).getContentType()  text/plain
07:39:24,376 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-921) ((SipServletResponse) message).getContent()   hello
07:39:24,376 ERROR [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-921) null: java.lang.NullPointerException
        at org.mobicents.servlet.restcomm.sms.SmsService.response(SmsService.java:445) [restcomm.sms-7.4.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.sms.SmsService.onReceive(SmsService.java:396) [restcomm.sms-7.4.0-SNAPSHOT.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

07:39:38,450 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (SIP-TCP-Core-PipelineThreadpool-15) <message
from="192.168.1.3:59673"
to="192.168.1.3:5082"
time="1445866778449"
isSender="false"
transactionId="z9hg4bk-3930-606cbedc0eaa0170d72e2358800d1e75"
callId="1445866778431"
firstLine="REGISTER sip:192.168.1.3 SIP/2.0"
>
<![CDATA[REGISTER sip:192.168.1.3 SIP/2.0
Call-ID: 1445866778431
07:40:00,824 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-930) P2P, Message from: alice redirected to
 registered client: charles
07:40:00,824 INFO  [com.telestax.servlet.MonitoringService] (RestComm-akka.actor.default-dispatcher-930) Processing Message: "org.mobicents.servlet.re
stcomm.telephony.TextMessage sender : class akka.actor.RepointableActorRef
07:40:00,854 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (SIP-TCP-Core-PipelineThreadpool-19) <message
from="192.168.1.3:59673"
to="192.168.1.3:5082"
time="1445866800854"
isSender="false"
transactionId="z9hg4bk578e2275_57a5b08a_f6cbde69-363d-452f-8083-3679d9834d3a"
callId="f1a6608d1e3c74b3994716ecd56600de@192.168.1.3"
firstLine="SIP/2.0 200 OK"
>
<![CDATA[SIP/2.0 200 OK
Call-ID: f1a6608d1e3c74b3994716ecd56600de@192.168.1.3
CSeq: 1 MESSAGE
From: <sip:alice@192.168.1.3>;tag=01029491_2c3efd52_57a5b08a_578e2275
To: <sip:charles@telestax.com>;tag=1445866800851
Max-Forwards: 70
Via: SIP/2.0/WS 192.168.1.3:5082;branch=z9hG4bK578e2275_57a5b08a_f6cbde69-363d-452f-8083-3679d9834d3a;rport
Content-Type: text/plain
Contact: <sip:charles@192.168.1.3:59673;transport=ws>
Content-Length: 7

from me]]>
</message>

07:40:00,855 INFO  [org.mobicents.servlet.sip.core.session.SipSessionImpl] (MSS-Executor-Thread-11) Invalidating the sip session (01029491_2c3efd52_57a5b08a_578e2275;f1a6608d1e3c74b3994716ecd56600de@192.168.1.3;578e2275;RestComm)
07:40:00,855 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-930) B2BUA: Got response:
 SIP/2.0 202 OK
 SIP/2.0 202 OK
Call-ID: f1a6608d1e3c74b3994716ecd56600de@192.168.1.3
CSeq: 1 MESSAGE
From: <sip:alice@192.168.1.3>;tag=01029491_2c3efd52_57a5b08a_578e2275
To: <sip:charles@telestax.com>;tag=1445866800851
Max-Forwards: 70
Via: SIP/2.0/WS 192.168.1.3:5082;branch=z9hG4bK578e2275_57a5b08a_f6cbde69-363d-452f-8083-3679d9834d3a;rport
Content-Type: text/plain
Contact: <sip:charles@192.168.1.3:59673;transport=ws>
Content-Length: 7

from me
07:40:00,855 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-930) response.getContentType() from me
07:40:00,856 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-930) response.getContentType() [B@4c42ff8
07:40:00,856 INFO  [org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper] (RestComm-akka.actor.default-dispatcher-930) response.getStatus() 202
07:40:00,856 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-929) getting INSTANCE OF class  class org.mobicents.servlet.sip.message.Servlet3SipServletResponseImpl
07:40:00,857 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-929) ((SipServletResponse) message).getContentType()  text/plain
07:40:00,857 INFO  [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-929) ((SipServletResponse) message).getContent()   from me
ent()   from me
07:40:00,857 ERROR [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-929) Can not bind object to session that ha
s been invalidated!!: java.lang.IllegalStateException: Can not bind object to session that has been invalidated!!
        at org.mobicents.servlet.sip.core.session.SipSessionImpl.setAttribute(SipSessionImpl.java:1230)
        at org.mobicents.servlet.sip.message.MobicentsSipSessionFacade.setAttribute(MobicentsSipSessionFacade.java:182)
        at org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper.forwardResponse(B2BUAHelper.java:402) [restcomm.telephony.api-7.4.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.sms.SmsService.response(SmsService.java:440) [restcomm.sms-7.4.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.sms.SmsService.onReceive(SmsService.java:396) [restcomm.sms-7.4.0-SNAPSHOT.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

07:40:02,311 INFO  [gov.nist.javax.sip.stack.SIPTransactionStack] (SIP-TCP-Core-PipelineThreadpool-20) <message
from="192.168.1.3:57895"
to="192.168.1.3:5082"
time="1445866802310"
isSender="false"
transactionId="z9hg4bk-343730-ad6cc84c48dcb9cba915a9179a57822f"
callId="1445866802299"
firstLine="REGISTER sip:192.168.1.3 SIP/2.0"
>
<![CDATA[REGISTER sip:192.168.1.3 SIP/2.0
Call-ID: 1445866802299

**Comment by croufay** [comment]
https://github.com/Mobicents/RestComm/commit/bd76e9eff3f10c7fa876d239aa93a6c86a5574c4
