### ISSUE TITLE
Handle SMPP NPE when no matching inbound DID is found or no SMS URL app

### ISSUE THREAD

**Issue by croufay** [Mobicents/RestComm#643]
18:03:55,541 INFO  [org.mobicents.servlet.restcomm.smpp.SmppHandlerProcessMessages] (SmppActorSystem-akka.actor.default-dispatcher-6) Inbound Message is received by the SMPP Handler
18:03:55,567 ERROR [org.mobicents.servlet.restcomm.smpp.SmppHandlerInboundForwarder] (RestComm-akka.actor.default-dispatcher-20) null: java.lang.NullPointerException
        at org.mobicents.servlet.restcomm.smpp.SmppHandlerInboundForwarder.HandleInboundMessages(SmppHandlerInboundForwarder.java:76) [restcomm.smpp-7.4.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.smpp.SmppHandlerInboundForwarder.onReceive(SmppHandlerInboundForwarder.java:209) [restcomm.smpp-7.4.0-SNAPSHOT.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

**Comment by croufay** [comment]
resolved

https://github.com/Mobicents/RestComm/commit/d3e61ad0049b01f1f878e6baa524fd90f6684554
