### ISSUE TITLE
No sound on a conference bridge from olympus.

### ISSUE THREAD

**Issue by leftyb** [Mobicents/RestComm#646]
There a problem with the sound on a conference call from Olympus. Conference number: +15124360170

Log files:

Restcomm While trying to connect to conference call three users (john, henrique, jean) with Olymous:
https://gist.github.com/leftyb/9cc95032ed9a3aa2a82b

Log from tcpdump traffic  :
https://gist.github.com/leftyb/2fc29a3a8c0757a79d6a

https://gist.github.com/leftyb/85e10f3570eeeec46193

**Comment by deruelle** [comment]
It looks like we face a conference split issue. The logs are located here https://app.box.com/s/hvy2w62mv1uc68dtxgo4pkkeyaaz11vj

The issue happened between 5:25 PM and 6 PM local server time in the logs. We see a conf created numbered 23 and 50 in MMS logs which I'm guessing are the 2 different conf being created.

**Comment by gvagenas** [comment]
@deruelle 
Checked the logs and here is what I see:

1. 17:25:20 someone disconnected from conference room cnf/50
```
2015-11-12 17:25:50,192 INFO  [MGCP] (service-scheduler-2) tx=147487711 Started, message= CRCX mobicents/bridge/$@172.17.0.24:2427, call agent = 92229c4b0ce0/172.17.0.24:2727
2015-11-12 17:25:50,212 INFO  [MGCP] (scheduler-worker-1) tx=147487711 was executed normaly
2015-11-12 17:25:50,218 INFO  [MGCP] (service-scheduler-1) tx=147487712 Started, message= MDCX mobicents/ivr/80@172.17.0.24:2427, call agent = 92229c4b0ce0/172.17.0.24:2727
2015-11-12 17:25:50,232 INFO  [MGCP] (scheduler-worker-3) tx=147487712 was executed normaly
2015-11-12 17:25:50,235 INFO  [MGCP] (service-scheduler-3) tx=147487713 Started, message= CRCX mobicents/bridge/84@172.17.0.24:2427, call agent = 92229c4b0ce0/172.17.0.24:2727
```

2. 17:25:50 someone creates a new call, I guess its the one previously dropped.
```2015-11-12 17:25:50,192 INFO  [MGCP] (service-scheduler-2) tx=147487711 Started, message= CRCX mobicents/bridge/$@172.17.0.24:2427, call agent = 92229c4b0ce0/172.17.0.24:2727```

3. 17:25:54  org.bouncycastle.crypto.tls.TlsFatalAlert exception occured:
```
org.bouncycastle.crypto.tls.TlsFatalAlert: internal_error(80)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source)
	at org.mobicents.media.server.impl.srtp.DtlsHandler$HandshakeWorker.run(DtlsHandler.java:343)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Handshake is taking too long! (>4000ms
	at org.mobicents.media.server.impl.srtp.NioUdpTransport.receive(NioUdpTransport.java:94)
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.receiveRecord(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.receive(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSReliableHandshake.receiveMessage(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source)
	... 3 more
```
Maybe this explains the no audio. There is no reference to a connection or endpoint for this exception so we cannot relate it to a call but I guess its from the call created few ms earlier

4. The call proceeds and Restcomm joins the call to the conference endpoint 50, the same cnf endpoint as the one at (1) where the call dropped.
```
2015-11-12 17:25:55,187 INFO  [MGCP] (service-scheduler-3) tx=147487716 Started, message= CRCX mobicents/bridge/84@172.17.0.24:2427, call agent = 92229c4b0ce0/172.17.0.24:2727
2015-11-12 17:25:55,192 INFO  [MGCP] (scheduler-worker-3) tx=147487716 was executed normaly
2015-11-12 17:25:55,196 INFO  [MGCP] (service-scheduler-1) tx=147487717 Started, message= MDCX mobicents/cnf/50@172.17.0.24:2427, call agent = 92229c4b0ce0/172.17.0.24:2727
2015-11-12 17:25:55,211 INFO  [MGCP] (scheduler-worker-0) tx=147487717 was executed normaly
```

5. Further down the log file I can see a lot of calls connecting and disconnecting again, but for the majority of the calls the conference endpoint is 50 which I think its the one for the conference call you had. There are other conference endpoints in the logs after 17:25 but not as many as the cnf/50 and I believe are calls to a different DID/Application.

To me Restcomm uses the correct conference endpoint but from the logs files I cannot tell with certainty because there is no relation between the call and the conference endpoint.
The pcap files are not the proper ones since they have traces for 19:18.

@hrosa did you had a look at the logs?

**Comment by gvagenas** [comment]
Can't reproduce the issue, seems latest patch on DTLS at MMS fixed that issue. In case this happens again we need pcap and logs to check.
