### ISSUE TITLE
Test Conference feature on Dialogic XMS

### ISSUE THREAD

**Issue by hrosa** [Mobicents/RestComm#659]
Test Conference (audio) feature on Dialogic XMS.

**Comment by hrosa** [comment]
JSR309 is failing to create a Media Mixer, required for the Conference. Call fails as result.
The stack trace is the following:

12:02:52,759 INFO  [org.mobicents.servlet.restcomm.telephony.Conference] (RestComm-akka.actor.default-dispatcher-617)  ********** Conference akka://RestComm/user/$c/$b Current State: uninitialized
12:02:52,760 INFO  [org.mobicents.servlet.restcomm.telephony.Conference] (RestComm-akka.actor.default-dispatcher-617)  ********** Conference akka://RestComm/user/$c/$b Processing Message: org.mobicents.servlet.restcomm.telephony.StartConference
12:02:52,758 ERROR [com.vendor.dialogic.javax.media.mscontrol.DlgcMediaSessionProxy] (RestComm-akka.actor.default-dispatcher-621) Failed to create MediaMixer: java.lang.NullPointerException
	at com.vendor.dialogic.javax.media.mscontrol.mixer.DlgcMediaMixerProxy.<init>(DlgcMediaMixerProxy.java:82) [dlgmsc-4.2.133.jar:4.2 Trunk Build 133 - Experimental]
	at com.vendor.dialogic.javax.media.mscontrol.mixer.DlgcMediaMixer.getProxy(DlgcMediaMixer.java:819) [dlgmsc-4.2.133.jar:4.2 Trunk Build 133 - Experimental]
	at com.vendor.dialogic.javax.media.mscontrol.DlgcMediaSessionProxy.createMediaMixer(DlgcMediaSessionProxy.java:261) [dlgmsc-4.2.133.jar:4.2 Trunk Build 133 - Experimental]
	at com.vendor.dialogic.javax.media.mscontrol.DlgcMediaSessionProxy.createMediaMixer(DlgcMediaSessionProxy.java:220) [dlgmsc-4.2.133.jar:4.2 Trunk Build 133 - Experimental]
	at org.mobicents.servlet.restcomm.mscontrol.jsr309.Jsr309ConferenceController$Initializing.execute(Jsr309ConferenceController.java:387) [restcomm.mscontrol.jsr309-7.4.0.1209.jar:]
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:100) [restcomm.commons-7.4.0.1209.jar:]
	at org.mobicents.servlet.restcomm.mscontrol.jsr309.Jsr309ConferenceController.onCreateMediaSession(Jsr309ConferenceController.java:311) [restcomm.mscontrol.jsr309-7.4.0.1209.jar:]
	at org.mobicents.servlet.restcomm.mscontrol.jsr309.Jsr309ConferenceController.onReceive(Jsr309ConferenceController.java:277) [restcomm.mscontrol.jsr309-7.4.0.1209.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
