### ISSUE TITLE
ERROR [org.mobicents.servlet.sip.core.dispatchers.DispatchTask] (Mobicents-SIP-Servlets-UDPMessageChannelThread-24) {60} Unexpected exception while processing message SIP/2.0 200 OK

### ISSUE THREAD

**Issue by RomanDS** [Mobicents/RestComm#768]
Above exception prevents from 200 OK to be processed in this case by Dialogic JSR 309 connector which causes Dialogic JSR 309 connector state to be in "TransitionState" and every call on that leg from this point on will error out.

20:50:21,067 DEBUG [com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipServlet] (Mobicents-SIP-Servlets-UDPMessageChannelThread-24) {154} Entering  DlgcSipServlet::doResponse
20:50:21,067 ERROR [org.mobicents.servlet.sip.core.dispatchers.DispatchTask] (Mobicents-SIP-Servlets-UDPMessageChannelThread-24) {60} Unexpected exception while processing message SIP/2.0 200 OK
From: "dlgjmc" <sip:dlgjmc@146.152.122.146:5080>;tag=04074160_4058d0e6_57a5b08a_1e8fb6f2
To: "MediaServer" <sip:msml=93791@146.152.122.168:5060>;tag=e771d368-a87a9892-13c4-65014-37-2e7cf509-37
Call-ID: 8beda6c3f77b01b66e134b76c3b43455@146.152.122.146
CSeq: 5 INFO
Via: SIP/2.0/UDP 146.152.122.146:5080;branch=z9hG4bK1e8fb6f2_57a5b08a_eb7e578c-028c-4b91-80ba-246d1db6232d
Allow: INVITE,CANCEL,ACK,BYE,OPTIONS,INFO,REFER,NOTIFY,UPDATE
User-Agent: XMS/3.0.11915
Contact: <sip:msml=93791@146.152.122.168:5060>
Content-Type: application/xml
Content-Length: 152
<?xml version="1.0" encoding="UTF-8"?>
<msml version="1.1">
<result mark="conn:e771d368-a87a9892-13c4-65014-37-2e7cf509-37" response="200"/>
</msml>: org.mobicents.servlet.sip.core.DispatcherException: Unexpected exception while processing response : SIP/2.0 200 OK
From: "dlgjmc" <sip:dlgjmc@146.152.122.146:5080>;tag=04074160_4058d0e6_57a5b08a_1e8fb6f2
To: "MediaServer" <sip:msml=93791@146.152.122.168:5060>;tag=e771d368-a87a9892-13c4-65014-37-2e7cf509-37
Call-ID: 8beda6c3f77b01b66e134b76c3b43455@146.152.122.146
CSeq: 5 INFO
Via: SIP/2.0/UDP 146.152.122.146:5080;branch=z9hG4bK1e8fb6f2_57a5b08a_eb7e578c-028c-4b91-80ba-246d1db6232d
Allow: INVITE,CANCEL,ACK,BYE,OPTIONS,INFO,REFER,NOTIFY,UPDATE
User-Agent: XMS/3.0.11915
Contact: <sip:msml=93791@146.152.122.168:5060>
Content-Type: application/xml
Content-Length: 152
<?xml version="1.0" encoding="UTF-8"?>
<msml version="1.1">
               <result mark="conn:e771d368-a87a9892-13c4-65014-37-2e7cf509-37" response="200"/>
</msml>
               at org.mobicents.servlet.sip.core.dispatchers.ResponseDispatcher$1.dispatch(ResponseDispatcher.java:503) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at org.mobicents.servlet.sip.core.dispatchers.DispatchTask.dispatchAndHandleExceptions(DispatchTask.java:58) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at org.mobicents.servlet.sip.core.dispatchers.ResponseDispatcher.dispatchMessage(ResponseDispatcher.java:524) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processResponse(SipApplicationDispatcherImpl.java:1118) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at gov.nist.javax.sip.EventScanner.deliverResponseEvent(EventScanner.java:317) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:148) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.DialogFilter.processResponse(DialogFilter.java:1514) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.stack.SIPClientTransactionImpl.nonInviteClientTransaction(SIPClientTransactionImpl.java:630) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.stack.SIPClientTransactionImpl.processResponse(SIPClientTransactionImpl.java:535) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.stack.SIPClientTransactionImpl.processResponse(SIPClientTransactionImpl.java:1622) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:611) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:514) [jain-sip-ri-1.2.259.jar:1.2.259]
               at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:319) [jain-sip-ri-1.2.259.jar:1.2.259]
               at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: java.lang.NullPointerException
               at org.mobicents.servlet.sip.message.SipServletMessageImpl.getSession(SipServletMessageImpl.java:1096) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at org.mobicents.servlet.sip.message.SipServletMessageImpl.getSession(SipServletMessageImpl.java:1083) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.processSipResponse(DlgcSipB2BUA.java:626)
               at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipServlet.doResponse(DlgcSipServlet.java:155)
               at javax.servlet.sip.SipServlet.service(SipServlet.java:334) [sip-servlets-spec-3.1.649.jar:3.1.649]
               at org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher.callServlet(MessageDispatcher.java:459) [sip-servlets-impl-3.1.649.jar:3.1.649]
               at org.mobicents.servlet.sip.core.dispatchers.ResponseDispatcher$1.dispatch(ResponseDispatcher.java:491) [sip-servlets-impl-3.1.649.jar:3.1.649]
               ... 14 more

**Comment by RomanDS** [comment]
Moved to SIP Servlets project: https://github.com/Mobicents/sip-servlets/issues/101
